10 add store functionality
sv053/GameTierra pull request #14
Opened 2022-02-17 18:43 UTC by sv053

2022-02-17 21:04 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/controller/GameController.java
> +    @GetMapping("/{game_id}/{user_id}")
get?

2022-02-17 21:05 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/controller/GameController.java
> +    public String buyGame(@PathVariable Integer game_id, @PathVariable Integer user_id) {
code style

2022-02-17 21:19 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/domain/repository/CreateManyAndBuyOneRepository.java
> +    Order createOrder(Order order);
What is this specific stuff doing in generic repository?

2022-02-17 21:20 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/domain/repository/GameRepository.java
> +        return 0;
what does it mean?

2022-02-17 21:20 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/domain/repository/GameRepository.java
> +        return null;
?

2022-02-17 21:25 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/domain/repository/db/DbGameRepository.java
> +    public Order createOrder(Order orderToAdd) {
breaks SRP

2022-02-17 21:34 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/domain/model/Order.java
> +    private Date date;
`Date` is obsolete

2022-02-17 21:35 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/domain/repository/Repository.java
> +    int update(T item);
Why update should return an `int`?

2022-02-19 19:35 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/domain/model/Order.java
> +        return Objects.equals(user, order.user) && Objects.equals(game, order.game) && Objects.equals(date, order.date);
One of the major fields is missing

2022-02-19 19:36 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/domain/repository/db/DbStoreRepository.java
> +public class DbStoreRepository {
Doesn't have any interface, but actually uses one of the APIs

2022-02-19 19:37 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/domain/repository/db/DbUserRepository.java
> +    public User update(User userToUpdate) {
The method fools clients, accepts an object but updates only a field

2022-02-19 19:37 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/domain/repository/db/DbUserRepository.java
> +        if (jdbcTemplate.update(UPDATE_USER_BALANCE
Clunky `if-else` block

2022-02-19 19:38 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/domain/repository/db/DbUserRepository.java
> +        else return null;
Why return `null`?

2022-02-19 19:43 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/service/StoreService.java
> +            if (updatedUser != null && createdOrder.getId() != null)
Is there any possibility to have an order without an id?

2022-02-19 19:44 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/domain/model/Order.java
> +    private Integer id;
can be final

2022-02-19 19:46 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/domain/repository/db/DbStoreRepository.java
> +    private static final String INSERT_ORDER = "INSERT into user_game (user_id, game_id, order_date) VALUES (?, ?, ?) ";
`StoreRepository` creates an entity with the name `order` and inserts into `user_game` (which is a name for join table)...

2022-02-19 19:47 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/domain/model/Order.java
> +    private LocalDate date;
Order should have time

2022-02-19 19:55 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/controller/StoreController.java
> +    public boolean buyGame(@PathVariable Integer game_id, @PathVariable Integer user_id) {
style №2

2022-02-19 19:58 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/domain/repository/db/DbUserRepository.java
> +                        + userToUpdate.getBalance()
Concats in query

2022-02-19 20:11 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/controller/StoreController.java
> +    public boolean buyGame(@PathVariable Integer game_id, @PathVariable Integer user_id) {
style №2

2022-02-21 15:16 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/domain/model/Order.java
> +        if ((!Objects.equals(id, order.id))
Weird statement, can be simplified

2022-02-21 15:17 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/domain/repository/Repository.java
> +public interface Repository<T, K> extends CreateOneRepository<T, K>{
formatting

2022-02-21 15:18 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/domain/repository/UpdateRepository.java
> +    Optional<T> updateColumn(T item);
update which column?

2022-02-21 15:19 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/domain/repository/UpdateRepository.java
> +    Optional<T> update(T item);
`Create` returns an object, `update` - updates an object, how a response can be optional?

2022-02-21 15:19 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/domain/repository/db/DbOrderRepository.java
> +public class DbOrderRepository {
no interface №2

2022-02-21 15:21 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/domain/repository/db/DbOrderRepository.java
> +    private static final String INSERT_ORDER = "INSERT into user_game (user_id, game_id, order_datetime) VALUES (?, ?, ?) ";
Why an order is inserted into `user_game`?

2022-02-21 15:22 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/domain/repository/db/DbUserRepository.java
>      private static final String INSERT_USER_QUERY = "INSERT into user (login, balance, tier_id) VALUES ( ?, ?, ?) ";
query formatting

2022-02-21 15:26 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/service/OrderService.java
> +    public Map<User,Game> buyGame(int gameId, int userId) {
I would suggest to return a `Transaction` with positive or negative status here to present it to a user

2022-02-21 15:27 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/domain/model/Order.java
> +    public LocalDateTime getDate() {
Method name does not fit

2022-02-21 15:28 UTC, AlexeyShutov commented on src/main/resources/gamesage_dll.sql
> +    'order_datetime'    DATETIME_INTERVAL_CODE,
format

2022-02-21 15:29 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/service/OrderService.java
> +        return Map.of(user, game);
Response is not user-friendly - no purchase info, moreover, if he has many games - it would be a nightmare to understand if a game is added or not

2022-02-23 20:10 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/domain/repository/UpdateRepository.java
> +    T updateUserBalanceColumn(T item);
Why such wide interface should know any details about some specific fields? Any implementor is forced now to update some user balance despite that only one has these details.

2022-02-23 20:13 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/domain/repository/db/DbOrderRepository.java
> +@org.springframework.stereotype.Repository
import can be used

2022-02-23 20:14 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/domain/repository/db/DbOrderRepository.java
> +public class DbOrderRepository implements CreateOneRepository<Order, Integer> {
Saved orders should be accessible from REST API

2022-02-23 20:15 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/domain/repository/db/DbUserRepository.java
> +    private static final String UPDATE_USER = "UPDATE user SET login = ?, balance = ?, tier_id = ?  " +
Login is rarely acceptable to change

2022-02-23 20:16 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/domain/repository/db/DbUserRepository.java
> +        Optional<User> retrievedUser = findById(userToUpdate.getId());
So, you're updating a user then checking its presence?

2022-02-23 20:17 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/service/OrderService.java
> +    private final DbOrderRepository storeRepository;
Specific class injection

2022-02-23 20:18 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/service/OrderService.java
> +    public class PurchaseResult {
No encapsulation

2022-02-23 20:18 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/service/OrderService.java
> +        public boolean result;
This is not a result

2022-02-23 20:19 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/service/OrderService.java
> +        public Game lastGame;
target game, not last game. This is a single result, it doesn't accumulates history.

2022-02-23 20:20 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/service/OrderService.java
> +        public User user;
Not any user, buyer

2022-02-23 20:22 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/service/OrderService.java
> +            purchaseResult.message = "the balance is " + user.getBalance()
You already have this data, why to repeat?

2022-02-23 20:23 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/service/OrderService.java
> +                storeRepository.createOne(new Order(null, user, purchaseResult.lastGame, LocalDateTime.now()));
overload the constructor

2022-02-23 20:25 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/service/OrderService.java
> +        PurchaseResult purchaseResult = new PurchaseResult();
This is a good case for a builder pattern

2022-02-23 20:27 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/service/OrderService.java
> +        purchaseResult.lastGame = gameService.findById(gameId);
The saved line of code leads to longer statements and sabotages further code readability, extract to a variable

2022-02-23 20:28 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/service/OrderService.java
> +        if (user.canPay(price)) {
Try to simplify it, long and nested branches could be avoided

2022-02-23 20:30 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/service/OrderService.java
> +        purchaseResult.user = userService.findById(userId);
excessive db call

2022-02-23 20:30 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/service/UserService.java
> +            users.add(findById(u.getId()));
What is this for?

2022-02-23 20:32 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/service/UserService.java
> +    private final DbGameRepository gameRepository;
Inject only directly related repositories, the rest operations should go via services

2022-02-23 20:33 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/service/UserService.java
> +        retrievedUser.setGames(Set.copyOf(userGames));
you can do this...or you can leave the set final, and add all games to it, equivalent operation of `Set.copy`

2022-02-23 20:34 UTC, AlexeyShutov commented on src/main/resources/gamesage_dll.sql
> +    'login'             TEXT NOT NULL CHECK ('login' != ''),
Login should be unique btw

2022-02-23 20:34 UTC, AlexeyShutov commented on src/test/java/com/gamesage/store/service/UserServiceTest.java
> +//    @Test
?

2022-02-23 20:38 UTC, AlexeyShutov commented on src/test/java/com/gamesage/store/service/GameServiceTest.java
>  package com.gamesage.store.service;
1. Order service is not test-covered
2. Some tests are failing

2022-02-23 20:45 UTC, AlexeyShutov requested changes
- Some tests are failing
- Order service is not test-covered
- The rest remarks are in separate comments

2022-02-25 15:10 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/domain/repository/UpdateRepository.java
> +    User update(User user);
Again, update repository is a wide interface, why it should know anything about `User`?

2022-02-25 15:11 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/domain/repository/UserRepository.java
> -import com.gamesage.store.domain.model.User;
This is not the scope of this PR

2022-02-25 15:17 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/domain/repository/db/DbGameRepository.java
> +            userGames.add(findById(gameId).orElseThrow(() -> new EntityNotFoundException(gameId)));
Very ineffective way to fetch the games

2022-02-25 15:18 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/domain/repository/db/DbOrderRepository.java
> +            ps.setInt(1, orderToAdd.getUser().getId());
You can create helper methods for these ids

2022-02-25 15:20 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/domain/repository/db/DbOrderRepository.java
> +                    null);
Where is the missing data?

2022-02-25 15:22 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/domain/repository/db/DbUserRepository.java
> +        Optional<User> retrievedUser = findById(userToUpdate.getId());
Added to a wrong layer

2022-02-25 15:31 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/service/OrderService.java
> +        userService.findById(userId);
Why do you need this call?

2022-02-25 15:34 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/domain/model/PurchaseIntent.java
> +    private boolean status;
Status should have values, this is a flag. Think of a proper name.

2022-02-25 15:40 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/domain/model/PurchaseIntent.java
> +    private Order order;
I don't think `Order` adds much value here. Repeats part of the info you have. You can include the time here though.

2022-02-25 15:50 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/service/OrderService.java
> +                        .buyer(userService.updateBalance(user))
Extract and put right after user operations

2022-02-25 15:52 UTC, AlexeyShutov commented on src/main/resources/gamesage_dll.sql
> +    'level'             TEXT NOT NULL CHECK ('level' != '') UNIQUE,
We agreed to rename it 'level' -> 'name', didn't we?

2022-02-25 15:58 UTC, AlexeyShutov commented on src/test/java/com/gamesage/store/service/OrderServiceDbIntegrationTest.java
> +        List<Order> allOrdersInTheTable = orderService.findAll();
so if the table is empty, the test should be green?

2022-02-25 15:58 UTC, AlexeyShutov commented on src/test/java/com/gamesage/store/service/OrderServiceDbIntegrationTest.java
> +        assertAll(
why not assert equals on objects?

2022-02-27 07:07 UTC, AlexeyShutov commented on src/test/java/com/gamesage/store/service/OrderServiceDbIntegrationTest.java
> +    User userToCreate;
Modifiers, new lines, order... First should be the dependencies, then helper data

2022-02-27 07:09 UTC, AlexeyShutov commented on src/test/resources/schema.sql
> +    id              INTEGER PRIMARY KEY AUTO_INCREMENT,
formatting

2022-02-27 07:11 UTC, AlexeyShutov commented on src/test/java/com/gamesage/store/service/OrderServiceDbIntegrationTest.java
> +        userToCreate = new User(null, "aqua", new Tier(
The scope of this field can be narrowed down

2022-02-27 07:21 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/service/OrderService.java
> +        String message = "play now!";
Use Enum with predefined messages instead

2022-02-27 11:12 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/domain/model/PurchaseIntent.java
> +        PLAY_NOW,
A message may be long and this is not how users want to read it, they should have a separate name for internal purposes (code) and a message text for clients

2022-02-27 11:13 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/domain/model/PurchaseIntent.java
> +    public enum Message {
A message may be long and this is not how users want to read it, they should have a separate name for internal purposes (code) and a message text for clients

2022-02-27 11:22 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/domain/repository/GameRepository.java
>      public List<Game> create(List<Game> gamesToAdd) {
This method is not in interface anymore

2022-02-27 11:32 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/service/OrderService.java
> +                message = PurchaseIntent.Message.IS_ALREADY_OWNED;
Use imports

2022-02-27 11:33 UTC, AlexeyShutov commented on src/test/java/com/gamesage/store/service/OrderServiceDbIntegrationTest.java
> +    private GameService gameService;
New line

2022-02-27 11:34 UTC, AlexeyShutov commented on src/test/java/com/gamesage/store/service/OrderServiceDbIntegrationTest.java
> +        orderService.buyGame(game.getId(), user.getId());
What is this line for?

2022-02-27 11:38 UTC, AlexeyShutov commented on src/test/java/com/gamesage/store/service/OrderServiceDbIntegrationTest.java
> +                        .orderDateTime(result.getOrderDateTime())
That is not right...You're testing actual value against itself. You should test expected values against actual values. It's equivalent if you'll write `result == result` and it always will be green. The purpose of the tests is not to be always green but to find bugs.

2022-03-01 12:36 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/domain/model/PurchaseIntent.java
> +        THE_GAME_PRICE_IS_HIGHER_THAN_THE_BALANCE("Sorry, your balance is not enough to buy the game");
Simply `NOT_ENOUGH_BALANCE`, no need for a long names if you can make it compact

2022-03-01 12:37 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/domain/model/PurchaseIntent.java
> +        private String message;
This should be an `Enum`, what is the point of making it `string`?

2022-03-01 12:42 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/service/OrderService.java
> +        if (canBuy) {
use guard statements, no need to extract in these case, method name is laconic enough

2022-03-01 12:53 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/service/OrderService.java
> +    public PurchaseIntent buyGame(int gameId, int userId, LocalDateTime dateTime) {
That is some weird API... Why service should accept this time instead of generating it? I know that it was done for testing, but this makes it weird for usage now

2022-03-01 12:53 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/service/OrderService.java
> +    public Order createNewOrder(User user, Game game, LocalDateTime dateTime) {
Public factory method in service...

2022-03-01 21:47 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/domain/model/PurchaseIntent.java
> +    private final String message;
Make this `Message` object as well

2022-03-01 21:52 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/service/OrderService.java
> +        saveOrder(order);
Order saved even if the game is not owned

2022-03-01 21:57 UTC, AlexeyShutov commented on src/test/java/com/gamesage/store/service/GameServiceDbIntegrationTest.java
> +        Integer randomForName = new Random().nextInt(LocalDateTime.now().getNano());
You don't need a random data here

2022-03-01 21:58 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/service/OrderService.java
> +    private Game retrieveGame(int id) {
Redundant method

2022-03-01 22:01 UTC, AlexeyShutov commented on src/test/java/com/gamesage/store/service/OrderServiceDbIntegrationTest.java
> +        Thread.sleep(5);
There are no async/multithreaded calls methods, what is this for?

2022-03-01 22:02 UTC, AlexeyShutov commented on src/test/java/com/gamesage/store/service/OrderServiceDbIntegrationTest.java
> +                () -> assertTrue(expectedResult.getOrderDateTime().minusSeconds(1).isBefore(result.getOrderDateTime())),
`LocalDateTime.now()` is also before 9999-31-12

2022-03-01 22:04 UTC, AlexeyShutov commented on src/test/java/com/gamesage/store/service/OrderServiceDbIntegrationTest.java
> +        Order order = orderService.createNewOrder(user, game);
What is this order doing here?

2022-03-01 22:06 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/service/OrderService.java
> +    private void pay(User user, Game game) {
Order of the methods

2022-03-01 22:22 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/service/OrderService.java
> +    public Order createNewOrder(User user, Game game) {
How does this help you?

2022-03-01 22:29 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/service/OrderService.java
> +    private PurchaseIntent.Message createPurchaseMessage(boolean canPay, boolean hasGame) {
you're not creating anything here

2022-03-02 13:22 UTC, sv053 commented on src/main/java/com/gamesage/store/service/OrderService.java
> +        if (canBuy) {
the method uses it twice

2022-03-02 13:50 UTC, AlexeyShutov commented on src/test/java/com/gamesage/store/service/OrderServiceDbIntegrationTest.java
> +                () -> assertTrue(expectedResult.getOrderDateTime().isAfter(result.getOrderDateTime())),
Would be better to create a helper method that checks between `before` date, current time and the actual date

2022-03-02 13:59 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/domain/model/PurchaseIntent.java
> +        private String message;
`final` can stay

2022-03-02 14:00 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/domain/model/PurchaseIntent.java
> +        private PurchaseMessage(String message) {
`private` is a redundant constructor modifier for enums

2022-03-02 14:01 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/domain/model/PurchaseIntent.java
> +    @JsonFormat(shape = JsonFormat.Shape.OBJECT)
That would lead to serialization of enum as an object with nested string

2022-03-02 14:01 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/domain/model/User.java
> +    public void setGames(List<Game> games) {
Well, this is not setter anymore then

2022-03-02 14:10 UTC, AlexeyShutov commented on src/test/java/com/gamesage/store/service/OrderServiceDbIntegrationTest.java
> +        Thread.sleep(5);
Not resolved

2022-03-02 14:11 UTC, AlexeyShutov commented on src/test/java/com/gamesage/store/service/OrderServiceDbIntegrationTest.java
> +        Order order = new Order(user, game);
Why do you even need this order?

2022-03-02 14:13 UTC, AlexeyShutov commented on src/test/java/com/gamesage/store/service/OrderServiceDbIntegrationTest.java
> +                () -> assertTrue(LocalDateTime.now().isAfter(result.getOrderDateTime())),
You don't need to call `now()` twice, because those are two different moments. You need to capture a moment before creation and check that the order date is between the moment and now

2022-03-02 20:05 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/service/UserService.java
> +        User user = null;
This doesn't make much sense, if user will be null, the exception will be thrown

2022-03-02 20:06 UTC, AlexeyShutov commented on src/test/java/com/gamesage/store/service/OrderServiceDbIntegrationTest.java
> +                () -> assertTrue(timePoint.minusSeconds(10).isBefore(result.getOrderDateTime())),
Just use `now()` here, extract both statements into a helper method

2022-03-02 20:11 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/service/OrderService.java
> +    private boolean ifCanBuy(boolean canPay, boolean hasGame) {
ordering

2022-03-02 20:12 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/service/OrderService.java
> +    private PurchaseIntent.PurchaseMessage preparePurchaseMessage(boolean canPay, boolean hasGame) {
ordering

2022-03-02 20:12 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/service/OrderService.java
> +    private void pay(User user, Game game) {
Not resolved

2022-03-02 20:18 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/service/OrderService.java
> +        PurchaseIntent.PurchaseMessage purchaseMessage = preparePurchaseMessage(canPay, hasGame);
Imports

2022-03-03 10:18 UTC, AlexeyShutov commented on src/test/java/com/gamesage/store/service/OrderServiceDbIntegrationTest.java
> +        compareDateTime(timePoint, result.getOrderDateTime());
Why this is not a part of `assertAll`? + the naming would be better, like `assertBetween` or smth like that

2022-03-03 10:37 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/service/OrderService.java
> +    private void pay(User user, Game game) {
->

2022-03-03 10:38 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/domain/model/PurchaseIntent.java
> +        @JsonValue
better to place it on the field itself, easier to find

2022-03-03 10:38 UTC, AlexeyShutov approved these changes

2022-03-03 11:08 UTC, merged