18 implement custom token auth
sv053/GameTierra pull request #19
Opened 2022-10-18 14:58 UTC by sv053

2022-10-18 18:55 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/controller/TokenController.java
> +public class TokenController {
Not needed, you already have login controller. Login controller makes auth, returns token if auth is successful, client proceeds with the token.

2022-10-18 18:56 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/domain/model/User.java
> +    private String token;
I remember we agreed to get rid of the token here and make it a separate entity.

2022-10-18 19:01 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/security/config/AuthenticationFilter.java
> +public class AuthenticationFilter {
I'm confused why you have 2 filters, but this one isn't registered within spring container

2022-10-18 19:02 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/security/config/AuthenticationFilter.java
> +        Optional username = Optional.fromNullable(httpRequest.getHeader("X-Auth-Username"));
We don't need dual auth possibility here. The only place you allow user-pass auth is `/login` controller, the rest authentication procedures (including filters) are operating on tokens

2022-10-18 19:04 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/security/config/Authenticator.java
> +public class Authenticator extends UsernamePasswordAuthentication {
I don't think this is needed. `/login` controller should respond with token data

2022-10-18 19:05 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/security/config/CurrentlyLoggedUser.java
> +public @interface CurrentlyLoggedUser {
What is this for?

2022-10-18 19:07 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/security/config/provider/AuthenticationProvider_.java
> +@Configuration
What is this config doing? Why does it have logic?

2022-10-18 19:08 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/security/model/VerificationToken.java
> +public class VerificationToken {
`AuthToken`, not `Verification`

2022-10-18 19:14 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/security/model/VerificationToken.java
> +    public String generateToken() {
This could be literally one-liner

2022-10-18 19:17 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/security/service/AuthService.java
>      public boolean checkIfUserExists(String login, String pass) {
This should be rewritten to auth instead and provide token

2022-10-18 19:19 UTC, AlexeyShutov requested changes
Follow suggestions from the comments

2022-10-19 23:49 UTC, sv053 commented on src/main/java/com/gamesage/store/security/config/provider/AuthenticationProvider_.java
> +@Configuration
Just a component?

2022-10-21 14:04 UTC, AlexeyShutov commented on pom.xml
> +        <dependency>
Duplicate dependency

2022-10-21 14:04 UTC, AlexeyShutov commented on pom.xml
> +        <dependency>
Why do you need sb cache?

2022-10-21 14:05 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/controller/GameController.java
> +    public List<Game> createGames(@RequestBody List<Game> gamesToSave, AppUser currentUser) {
`currentUser` not used

2022-10-21 14:06 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/controller/TokenController.java
> +public class TokenController {
I remember I mentioned that this is redundant controller

2022-10-21 14:09 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/controller/TokenController.java
> +    public User getToken(@RequestParam("username") final String username) {
Plus this is a tremendous security hole, not protected endpoint that gives away tokens for any users?

2022-10-21 14:26 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/controller/TokenController.java
> +    public User getToken(@RequestParam("username") final String username) {
An endpoint that gives away tokens for any users, this is a tremendous security hole

2022-10-21 14:29 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/controller/LoginController.java
>              return new ResponseEntity<>(user, HttpStatus.OK);
How logged-in user suppose to know his token? It's not in the response.

2022-10-21 14:33 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/domain/repository/TokenRepository.java
> +    AuthToken createToken(int userId);
This should not be a part of repo contract, why repo suppose to create tokens? It persists, retrieves and deletes entities

2022-10-21 14:34 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/domain/repository/db/DbTokenRepository.java
> +    private final BCryptPasswordEncoder encoder;
What's encoding doing here?

2022-10-21 14:36 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/security/config/auth/AuthProvider.java
> +public class AuthProvider implements AuthenticationProvider {
This auth provider is not working

2022-10-21 14:42 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/security/model/AuthToken.java
> +public class AuthToken extends AbstractAuthenticationToken {
Not sure why this inheritance is needed, it's never used and doesn't fulfill parent's contract.

2022-10-21 14:43 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/security/model/AuthToken.java
> +        return new StringBuilder()
Spring builder is not needed here

2022-10-21 14:43 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/security/model/AuthToken.java
> +        return token != null ? token.equals(authToken.token) : authToken.token == null;
simply `Objects.equals(token, authToken.token)`

2022-10-21 14:45 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/security/model/AuthToken.java
> +    private long id;
you don't need an ID for token, `userId` is an identifier. You can't have more than 1 token per user

2022-10-21 14:46 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/security/model/AuthToken.java
> +    private String token;
It's confusing to name an object's fields the same (almost, in this case) as the object itself. It should be called `value` or `tokenValue` at least

2022-10-21 14:47 UTC, AlexeyShutov commented on src/main/resources/application.properties
> +
extra new line

2022-10-21 14:48 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/security/service/AuthService.java
> +    public AuthToken updateToken(int userId) {
The name of service's method and repo's methods are contradicting each other

2022-10-21 14:50 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/security/service/AuthService.java
> +    public AuthToken findToken(int userId) {
Two overloaded methods in repo, should specify names more carefully

2022-10-21 14:52 UTC, AlexeyShutov requested changes
- Last test run `[ERROR] Tests run: 38, Failures: 0, Errors: 13, Skipped: 0`
- Comments

2022-10-23 12:01 UTC, sv053 commented on src/main/java/com/gamesage/store/controller/TokenController.java
> +    public User getToken(@RequestParam("username") final String username) {
Not really, it's based on the method checking if the user exists (userService->findById)

2022-10-23 12:19 UTC, sv053 commented on src/main/java/com/gamesage/store/domain/repository/TokenRepository.java
> +    AuthToken createToken(int userId);
but a rep is for CRUD and CRUD's C stands for create, doesn't it?

2022-10-23 13:06 UTC, sv053 commented on src/main/java/com/gamesage/store/domain/repository/TokenRepository.java
> +    AuthToken createToken(int userId);
should createOne for User, Order and Game be renamed as well?

2022-10-25 08:36 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/controller/LoginController.java
>      public ResponseEntity<User> login(@RequestBody User user) {
This endpoint supposes to provide a user with a token in case of successful auth, but it doesn't. How a user suppose to know his token?

2022-10-25 13:41 UTC, AlexeyShutov requested changes
The main logic that is missing here is there is no token in the response. User should get a token when makes login, then it uses the token as a header value in the consequent requests.

2022-10-25 13:41 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/security/config/provider/AuthenticationProvider_.java
> +@Configuration
Yes

2022-10-25 13:49 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/security/config/auth/AuthFilter.java
> +        AuthToken token = new AuthToken(Integer.parseInt(httpServletResponse.getHeader("x-auth-token")));
You don't send `userId` in the header, you send token value.

2022-10-25 13:55 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/security/config/auth/AuthFilter.java
> +        return Collections.list(httpServletRequest.getHeaderNames()).stream()
The header name is case insensitive.

2022-10-28 15:04 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/controller/LoginController.java
> +        AuthToken authToken = new AuthToken(user);
This is a wrong sequence of actions, you're trying to create a token for not validated user credentials + NPE because you never pass (and should not) user id during the login

2022-11-05 16:55 UTC, AlexeyShutov requested changes
- This PR requires cleanup from irrelevant stuff: authrorization, unused dependencies, commented out code, debug system-outs 
- Application is not starting because of an error
- There are 13 test failures

2022-11-21 20:22 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/security/service/AuthService.java
> +            token = provideTokenForCheckedUser(user.getId());
You don't have user id here, it's not a populated user, treat it like a data object for login/pass.

2022-11-21 20:24 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/security/auth/manager/AuthManager.java
> +public class AuthManager implements AuthenticationManager {
You don't need an empty managed that does delegation. You just need to register your provider within the default one.

2022-11-21 20:27 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/security/auth/provider/TokenAuthProvider.java
> +    public Authentication authenticate(Authentication authentication) throws AuthenticationException {
This is a complete miss. 
1. You don't have usernames/password in your authentication implementation. It's user id and token.
2. Why try to match passwords? No password is provided on this stage already.
3. Why fetch token? Your actual `Authentication` is `AuthToken `.

2022-11-21 20:28 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/security/auth/filter/TransactionFilter.java
> +public class TransactionFilter extends AbstractAuthenticationProcessingFilter {
A different type of filter fits here better.

2022-11-25 18:22 UTC, AlexeyShutov commented on pom.xml
> -            <scope>test</scope>
?

2022-11-25 18:22 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/GameTierra.java
> +        String[] beanNames = ctx.getBeanDefinitionNames();
Remove debug logs

2022-11-25 18:22 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/controller/GameController.java
> +    @PreAuthorize("hasAuthority('ADMIN')")
Remove authZ, it's irrelevant

2022-11-25 18:47 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/controller/GameController.java
> +        var v = SecurityContextHolder.getContext();
cleanup

2022-11-25 18:49 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/controller/LoginController.java
> +    public ResponseEntity<?> login(@RequestBody User user) {
Why wildcard mask? Better to return an object with user data rather than a token, you already have token in the header

2022-11-25 18:50 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/domain/model/User.java
> +        this.password = password;
assigned to self

2022-11-25 18:52 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/domain/repository/TokenRepository.java
> +    Optional<AuthToken> retrieveByUserId(int userId);
why suddenly `get` terminology became `retrieve`?

2022-11-25 18:58 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/domain/repository/db/DbTokenRepository.java
> +                    user,
What is the purpose of this user object if it holds only id? Misleading. The second downside is the object you're trying to save/get is not intended for persistence, it has a relationship with the framework. That's why I used 2 objects in my branch, one for persistence, one for the auth operations.

2022-11-25 18:59 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/security/auth/converter/AuthConverter.java
> +public class AuthConverter implements AuthenticationConverter {
What is this?

2022-11-25 19:01 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/security/auth/HeaderName.java
> +    public static final String TOKEN_HEADER = "x-auth-token";
headers are case-insesentive, but `X-Auth-Token` looks neat.

2022-11-25 19:01 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/security/auth/filter/FilterChainExceptionHandler.java
> +public class FilterChainExceptionHandler extends OncePerRequestFilter {
Not used anywhere

2022-11-25 19:07 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/security/auth/filter/PreAuthenticationFilter.java
> +        return token == null ? ResponseEntity.notFound() : new AuthToken(token);
`ResponseEntity`? What spring security suppose to know about `ResponseEntity`? You should return `null` if token is null or empty. Use utilities

2022-11-25 19:08 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/security/auth/filter/PreAuthenticationFilter.java
> +        return token == null ? ResponseEntity.notFound() : new AuthToken(token);
Actually, you don't even need `AuthToken` object here. Just use token value string. And rewrite `AuthToken` to a model that is persistence friendly.

2022-11-25 19:08 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/security/config/WebSecurityConfig.java
> +    public PreAuthenticationFilter transactionFilter() throws Exception {
what is transaction?

2022-11-25 19:10 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/security/config/WebSecurityConfig.java
> +              //  .antMatchers(HttpMethod.POST, "/login").permitAll()
why commented?

2022-11-25 19:11 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/security/config/WebSecurityConfig.java
> +              //  .antMatchers(HttpMethod.POST, "/login").permitAll()
Why commented?

2022-11-25 19:12 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/security/config/WebSecurityConfig.java
> +    public void configure(WebSecurity web) throws Exception {
Don't really know why this is ignored here

2022-11-25 19:12 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/security/model/PreAuthToken.java
> +public class PreAuthToken extends PreAuthenticatedAuthenticationToken {
not used

2022-11-25 19:14 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/security/service/AuthService.java
> +            User persistedUser = userService.findByLogin(user.getLogin());
You're doing 2 similar queries for no reasons

2022-11-25 19:14 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/security/service/AuthService.java
> +        return userExists ? ResponseEntity.ok()
Response entity is a controller-level logic, why a service is building it?

2022-11-25 19:15 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/security/service/AuthService.java
> +    private AuthToken provideWithToken(User user) {
Ordering of the methods

2022-11-25 19:17 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/security/service/TokenService.java
> +    public UserDetails findUserDetailsByTokenValue(String tokenValue) {
Too many queries here. Would be better to store the login with token value, and you can get rid of one.

2022-11-25 19:18 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/security/service/TokenService.java
> +        return String.format("%s - %s", new Timestamp(System.currentTimeMillis()).getTime(), UUID.randomUUID());
Better to avoid whitespaces if they are not necessary

2022-11-25 19:22 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/security/service/TokenService.java
> +        return String.format("%s - %s", new Timestamp(System.currentTimeMillis()).getTime(), UUID.randomUUID());
`new Timestamp(System.currentTimeMillis()).getTime()` is just `System.currentTimeMillis()`, why complicate?

2022-11-25 19:28 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/domain/repository/TokenRepository.java
> +package com.gamesage.store.domain.repository;
The app is failing if there is no token in the database.

2022-11-27 15:47 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/security/config/WebSecurityConfig.java
> +    public PreAuthenticationFilter transactionFilter() throws Exception {
Why this was resolved? This word looks alien in this domain, you don't have any transaction mentions elsewhere.

2022-11-27 18:48 UTC, sv053 commented
There are two tokens in the db: 
1669568128833-aab1c33b-0e82-456c-b51d-41320d82b52c|admin2
1669573017446-faa2f2dc-c22e-48d7-935a-7023fe625c0d|admin3
Users without token: 
{
        "id": 2,
        "login": "admin", //"admin1", "admin4"
        "password": "letmein",
        "tier": {
            "cashbackPercentage": 0.0,
            "id": 1,
            "level": "FREE"
        },
        "balance": 815.16,
        "games": []
    }

2022-12-02 17:25 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/controller/UserController.java
> +        System.out.println();
?

2022-12-02 17:26 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/controller/LoginController.java
> +        HttpHeaders responseHeaders = new HttpHeaders();
This doesn't need to be declared separately, can be embedded into the response builder

2022-12-02 17:28 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/controller/LoginController.java
> +        return token.isEmpty() ? new ResponseEntity<>(user, HttpStatus.NOT_FOUND) :
This scenario is impossible, if credentials are wrong an exception will be thrown

2022-12-02 17:29 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/security/auth/HeaderName.java
> +public class HeaderName {
Add private constructors for constant/utility classes

2022-12-02 17:31 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/security/auth/filter/PreAuthenticationFilter.java
> +        return new SSAuthToken(httpServletRequest.getHeader(HeaderName.TOKEN_HEADER));
Consider redesigning this, `SSAuthToken` is not really needed

2022-12-02 17:31 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/security/auth/filter/PreAuthenticationFilter.java
> +    protected Object getPreAuthenticatedPrincipal(HttpServletRequest httpServletRequest) {
No checks for empty text

2022-12-02 17:31 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/security/model/AuthToken.java
> +public class AuthToken {
`AuthToken` is not a security model, doesn't belong to the package where it is resided

2022-12-02 17:32 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/security/model/AuthToken.java
> +    @JsonProperty
Why do you need this?

2022-12-02 17:37 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/security/service/AuthService.java
> +    public String loginUser(User user) {
This should return `AuthToken`, you can't even achieve a scenario where empty string is returned

2022-12-02 17:38 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/security/service/TokenService.java
> +public class TokenService {
`TokenService` is not a security service, doesn't belong to the package where it is resided

2022-12-02 17:41 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/security/service/TokenService.java
> +    private final UserService userService;
I would say that this doesn't belong here. User Details have nothing to do with token, yet they somehow ended up here.

2022-12-02 17:44 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/security/service/TokenService.java
> +    public String generateToken() {
That's better to be moved to `AuthToken`, it has no database interactions, has no dependencies on other services.

2022-12-02 17:46 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/security/service/AuthService.java
> +    public String loginUser(User user) {
A name term here would be `authenticate`

2022-12-02 17:48 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/security/service/AuthService.java
> +        Optional<AuthToken> token = tokenService.findTokenByLogin(user.getLogin());
Streams have fluent API, so use it

2022-12-02 17:48 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/security/service/AuthService.java
> +        return token.orElseGet(() -> tokenService.saveToken(new AuthToken(tokenService.generateToken(), user.getLogin())));
If you don't need a function, just use `orElse()`

2022-12-02 17:50 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/security/service/AuthService.java
> +public class AuthService implements AuthenticationUserDetailsService<PreAuthenticatedAuthenticationToken> {
I doubt that this inheritance is makes sense. Yes, the names are luckily similar, but in the end the inherited method is about `UserDetails`

2022-12-02 17:51 UTC, AlexeyShutov commented on src/main/resources/application.properties
> +logging.level.org.springframework.boot.autoconfigure=ERROR
Why logging level so low?

2022-12-02 17:54 UTC, AlexeyShutov requested changes
- Follow suggestions from the comments
- No new unit/integration tests for added classes

2022-12-05 13:17 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/security/service/AuthService.java
> +public class AuthService implements AuthenticationUserDetailsService<PreAuthenticatedAuthenticationToken> {
How exactly did you resolve this? I don't see any changes

2022-12-05 13:17 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/security/service/AuthService.java
> +        } catch (NullPointerException e) {
This is totally bad, you should never catch NPE.

2022-12-05 13:23 UTC, AlexeyShutov commented on src/main/resources/application.properties
> +logging.level.com.gamesage.store=trace
Why it's trace now? Why default log didn't work?

2022-12-05 15:30 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/security/service/AuthService.java
> +            encoder.matches(pass, storedUser.getPassword());
Doesn't really do any checks, passed with any password

2022-12-05 17:57 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/controller/LoginController.java
> +                .headers(httpHeaders ->
Can be much simpler - `.header( ... )`

2022-12-05 17:58 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/domain/repository/Repository.java
> +
?

2022-12-05 17:59 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/security/auth/filter/PreAuthenticationFilter.java
> +    protected Object getPreAuthenticatedPrincipal(HttpServletRequest httpServletRequest) {
There are no checks, why process empty tokens?

2022-12-05 18:22 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/security/auth/filter/PreAuthenticationFilter.java
> +        return new SSAuthToken(token);
This class is unused. The reason for this is current pre-authentication filter/provider. When the code from this filter is called, it wraps your token in `PreAuthenticatedAuthenticationToken` and eventually the call ends in `loadUserDetails(PreAuthenticatedAuthenticationToken token) `. As you can notice, you use only credentials there, and the principal is never populated, not used. So the wrapper itself `SSAuthToken` is really redundant in the current implementation.

2022-12-06 16:56 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/domain/repository/TokenRepository.java
> +    AuthToken saveToken(AuthToken AuthToken);
Fix variable (input param) naming conventions

2022-12-06 17:31 UTC, AlexeyShutov commented on src/test/java/com/gamesage/store/service/TokenServiceDbIntegrationTest.java
> +    void saveTokenValue_Success() {
This doesn't add anything to the suite, all the stuff here already tested in previous tests. Instead, save should test the stuff purely related to save - are token values persisted correctly?

2022-12-06 17:34 UTC, AlexeyShutov commented on src/test/java/com/gamesage/store/security/service/AuthServiceIntegrationTest.java
> +        assertNotNull(foundToken);
you can do more granular asserts here

2022-12-07 12:42 UTC, AlexeyShutov commented on src/test/java/com/gamesage/store/security/service/AuthServiceIntegrationTest.java
> +        assertNotNull(foundToken);
Check if the token value is not null.

2022-12-07 12:45 UTC, AlexeyShutov commented on src/test/java/com/gamesage/store/service/OrderServiceIntegrationTest.java
> +                && (dateTime.isBefore(LocalDateTime.now())
Capture `now` just once and use in both places

2022-12-07 12:46 UTC, AlexeyShutov commented on src/test/java/com/gamesage/store/service/TokenServiceIntegrationTest.java
> +                .orElseThrow(() -> new EntityNotFoundException(token.getUserLogin()));
That's wrong. Why throw exceptions in tests? Assert on optionals

2022-12-07 12:47 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/domain/repository/db/DbTokenRepository.java
> +    public AuthToken createOne(AuthToken AuthToken) {
param naming

2022-12-07 12:50 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/security/config/WebSecurityConfig.java
> +@EnableGlobalMethodSecurity(securedEnabled = true)
Why this was enabled?

2022-12-07 12:50 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/controller/LoginController.java
>  package com.gamesage.store.controller;
Disable security debug mode please

2022-12-07 14:27 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/security/config/WebSecurityConfig.java
> +                .addFilterBefore(new FilterChainExceptionHandler(), LogoutFilter.class);
Broken config for `FilterChainExceptionHandler` will cause 500 for any caught exceptions

2022-12-08 17:50 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/controller/LoginController.java
> +                .header(HeaderName.TOKEN_HEADER, authService.authenticateUser(user).getValue())
Move service call to a separate like, would be more readable

2022-12-08 17:52 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/service/UserService.java
> +    public UserDetails findUserByCredentials(String login, String pass) {
Why do you need `UserDetails` here? you have `findByLogin`

2022-12-08 17:54 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/service/UserService.java
> +    public UserDetails findUserDetailsByTokenValue(String tokenValue) {
This method looks redundant, you can easily fit all the login into the caller. Besides, why it's public?

2022-12-08 17:58 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/security/auth/filter/FilterChainExceptionHandler.java
> +        } catch (WrongCredentialsException e) {
You don't have to do that, an exception will be resolved just fine if you configure this class properly. Now you will get the same problem if you'll catch another exception. Fix the root problem - configuration

2022-12-08 18:00 UTC, AlexeyShutov commented on src/test/java/com/gamesage/store/service/TokenServiceIntegrationTest.java
> +        assertEquals(token, foundToken.get());
Now you returned to the same problem you've had in the beginning

2022-12-08 18:03 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/security/auth/filter/FilterChainExceptionHandler.java
> +    private static final Logger logger = LoggerFactory.getLogger(FilterChainExceptionHandler.class);
There is a logger in a parent class, use it

2022-12-08 18:03 UTC, AlexeyShutov requested changes
Follow suggestions

2022-12-08 22:57 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/security/config/WebSecurityConfig.java
> +    public PreAuthenticationFilter preAuthenticationFilter() throws Exception {
Exception is not thrown here, redundant

2022-12-08 23:03 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/security/auth/filter/FilterChainExceptionHandler.java
> +    protected void doFilterInternal(HttpServletRequest request, HttpServletResponse response, FilterChain filterChain) throws ServletException, IOException {
The declared exceptions are never thrown

2022-12-08 23:05 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/service/UserService.java
> +    public User findUserByCredentials(String login, String pass) {
Move that to the place where all find methods dwelling

2022-12-08 23:13 UTC, AlexeyShutov commented on src/test/java/com/gamesage/store/service/TokenServiceIntegrationTest.java
> +        assertEquals(tokenToFind, foundToken.orElse(null));
this is better, but you don't need to compare objects, just compare optional to optional.
`assertEquals(Optional.of(tokenToFind), foundToken);`

2022-12-09 13:08 UTC, AlexeyShutov approved these changes

2022-12-19 21:11 UTC, merged

2023-03-30 19:57 UTC, AlexeyShutov commented on src/test/java/com/gamesage/store/service/TokenServiceIntegrationTest.java
> +        AuthToken tokenToFind = tokenService.createToken(token);
Bad naming here, I lost the plot reading it - which token is which