with controllers
sv053/GameTierra pull request #7
Opened 2021-11-29 22:38 UTC by sv053

2021-11-30 11:39 UTC, AlexeyShutov commented on pom.xml
> -            <artifactId>spring-boot-starter-log4j2</artifactId>
why?

2021-11-30 11:43 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/controller/GameController.java
> +    private final Logger logger = LoggerFactory.getLogger(getClass());
loggers are usually static

2021-11-30 11:44 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/controller/GameController.java
> +    private final GameRepository gameRepository;
We do you even need services in this scenario?

2021-11-30 11:46 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/controller/GameController.java
> +        gamesToSave.stream().forEach(u -> logger.info(u.toString()));
Don't produce excessive logging that doesn't bring any useful info

2021-11-30 11:47 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/controller/GameController.java
> +        if(game.isPresent()){
This is just broken

2021-11-30 11:48 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/controller/GameController.java
> +    @PostMapping("/createGames")
You don't need to specify actions with names, you have verbs in REST for this. The only exclusions are the endpoints that cannot be described by the rest verbs.

2021-11-30 11:51 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/controller/GameController.java
> +    public Game findGameById(@RequestParam Integer id) {
Instead of parameter - the ID could be a part of the path

2021-11-30 11:53 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/controller/UserController.java
> +        if(userRepository.findById(id).isPresent()){
2 queries to repo just to check if user exists?

2021-11-30 11:54 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/domain/model/Game.java
> -    public Game(String name, BigDecimal price) {
That was a bad move, it's always nice to have a reloaded stuff to indicate parameters with default values

2021-11-30 11:55 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/controller/GameController.java
> +    public List<Game> createGames(@RequestBody List<Game> gamesToSave){
Formatting

2021-11-30 11:55 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/controller/GameController.java
> +import com.gamesage.store.domain.data.sample.SampleData;
redundant

2021-11-30 11:58 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/domain/repository/UserRepository.java
> +    public void createUser(User user){
1. Looks like this repo doesn't assign any IDs to users
2. Create should return the results

2021-11-30 12:00 UTC, AlexeyShutov requested changes
Changes are proposed/indicated in the comments

2021-11-30 20:25 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/domain/repository/Repository.java
> +    List<T> find();
We already had one long discussion about `findBy`, now this one is even more confusing

2021-11-30 20:26 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/controller/GameController.java
> +    @PostMapping("/read/{id}")
`POST` for fetching a resource?

2021-11-30 20:26 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/controller/GameController.java
> +    @PostMapping("/create")
These are still redundant, the REST verbs are already set

2021-11-30 20:27 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/controller/UserController.java
> +    private static final Logger logger = LoggerFactory.getLogger(UserController.class);
Wrong order

2021-11-30 20:28 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/controller/UserController.java
> +        userService.createAll(List.of(user));
Why not to add a method for a single user?

2021-11-30 20:34 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/controller/UserController.java
> +        UserController.logger.info("User: " + user);
full names again

2021-11-30 20:35 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/controller/UserController.java
> +        UserController.logger.info("There are " + users.size() + " users");
Such logs would kill your machine in prod

2021-11-30 20:37 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/domain/model/Game.java
> +    public Game(){
There is a more graceful way to solve the deserialization problem

2021-11-30 20:38 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/controller/UserController.java
> +        UserController.logger.info("There are " + users.size() + " users");
What is the use of this log?

2021-11-30 20:38 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/domain/data/sample/SampleData.java
> +                new Game(null,"THE_WITCHER", BigDecimal.valueOf(17.28d)),
No changed back

2021-11-30 23:27 UTC, sv053 commented on src/main/java/com/gamesage/store/controller/UserController.java
> +    private static final Logger logger = LoggerFactory.getLogger(UserController.class);
PSF pattern?

2021-12-01 11:16 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/controller/GameController.java
> +    @PostMapping("/")
Why adding this rudiment to URI?

2021-12-01 11:17 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/controller/GameController.java
> +        return gameService.findAll();
Why anyone would want to see all the database after creating a bunch of games?

2021-12-01 11:17 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/controller/GameController.java
> +        Game game = gameService.findById(id);
Redundant var

2021-12-01 11:18 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/controller/UserController.java
> +    @PostMapping("/userslist")
I really don't see a use case for creating multiple users at once

2021-12-01 11:19 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/controller/GameController.java
> +    public List<Game> findGames(){
find what games?

2021-12-01 11:20 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/domain/model/Game.java
> +    static final long serialVersionUID = 1L;
Why do you need serialVersionUID?

2021-12-01 11:22 UTC, AlexeyShutov commented on src/test/java/com/gamesage/store/domain/repository/GameRepositoryTest.java
> +        assertEquals(games.size(), repository.findAll().size());
Why making multiple requests?

2021-12-01 11:24 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/controller/UserController.java
> +        return users;
A client doesn't want to see the users he sends, but created users

2021-12-01 11:26 UTC, AlexeyShutov requested changes
1. Design issues mentioned in the comments
2. Code is not formatted in many places
3. Unused imports in multiple files

2021-12-02 10:58 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/controller/GameController.java
> +    @PostMapping("")
An empty path is redundant

2021-12-02 11:00 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/domain/model/Game.java
> +    private Integer id;
ID usually is the first field

2021-12-02 11:03 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/controller/UserController.java
> +public class UserController {
Requested changes are not applied to the controller's methods

2021-12-02 11:07 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/domain/repository/GameRepository.java
> +        return Optional
The first operation may stay on the same line

2021-12-02 11:08 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/service/GameService.java
> +public class GameService{
->

2021-12-02 11:12 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/domain/model/Game.java
>  public class Game {
You're missing a separator in `toString` between `id` and `name`

2021-12-02 11:16 UTC, AlexeyShutov commented on src/test/java/com/gamesage/store/domain/repository/GameRepositoryTest.java
> -        assertEquals(games.size(), repository.getAll().size());
I didn't tell that you don't need to assert the size, because `containsAll` tests only the sub-list, and there are no guarantees that no duplicates are created

2021-12-02 11:26 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/domain/repository/AddManyRepository.java
> +public interface AddManyRepository<T, K> extends Repository<T, K>{
` `

2021-12-02 11:41 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/domain/repository/AddManyRepository.java
> +public interface AddManyRepository<T, K> extends Repository<T, K>{
I'm not sure that `add` gives a good context here, you have a limited functionality that just creates new entities and doesn't merge the changes

2021-12-02 20:12 UTC, AlexeyShutov commented on src/main/java/com/gamesage/store/controller/GameController.java
> +public class GameController {
Follow similar order for methods like in repo/services, it is easier to find everything when a controller grows

2021-12-02 20:12 UTC, AlexeyShutov approved these changes

2021-12-02 20:50 UTC, merged